services:
  dev:
    user: vscode
    environment:
      GRADLE_USER_HOME: /home/vscode/.gradle
    volumes:
      - ../:/workspace:cached
      - gradle-cache:/home/vscode/.gradle

volumes:
  gradle-cache:




